namespace Carbon.Media
{
    public enum CodecId
    {
        Unknown = 0,

        // -------------------- Audio Codecs ---------------------------------------
        _8svxExp       = 86071, // 8SVX exponential
        _8svxFib       = 86072, // 8SVX fibonacci
        AdpcmImaOki    = 71681,
        AdpcmDtk       = 71682, // ADPCM Nintendo Gamecube DTK
        AdpcmImaRad    = 71683, // ADPCM IMA Radical
        AdpcmG726Le    = 71684,
        AdpcmThpLe     = 71685, // ADPCM Nintendo THP
        AdpcmPsx       = 71686,
        AdpcmAica      = 71687,
        AdpcmImaDat4   = 71688,
        AdpcmMtaf      = 71689,
        Adpcm4xm       = 69639, // ADPCM 4X Movie
        AdpcmAdx       = 69641, // SEGA CRI ADX ADPCM
        AdpcmAfc       = 71680, // ADPCM Nintendo Gamecube AFC
        AdpcmCT        = 69644, // ADPCM Creative Technology
        AdpcmEa        = 69642, // ADPCM Electronic Arts
        AdpcmEaMaxisXa = 69658,
        AdpcmEaR1      = 69652, // ADPCM Electronic Arts R1
        AdpcmEaR2      = 69654, // ADPCM Electronic Arts R2
        AdpcmEaR3      = 69653, // ADPCM Electronic Arts R3
        AdpcmEaXas     = 69657, 
        AdpcmImaApc    = 69661,
        AdpcmImaEASead = 69655,
        AdpcmImaEAEacs = 69656, 
        AdpcmImaIss    = 69659,
        AdpcmImaAmv    = 69651,
        AdpcmImaQT     = 69632,
        AdpcmImaWav    = 69633, // ADPCM IMA WAV
        AdpcmImaDk3    = 69634, // ADPCM IMA Duck DK3
        AdpcmImaDk4    = 69635, // ADPCM IMA Duck DK4
        AdpcmImaWs     = 69636,
        AdpcmImaSmJpeg = 69637,
        AdpcmMS        = 69638, // ADPCM Microsoft
        AdpcmSbpro2    = 69649, // ADPCM Sound Blaster Pro 2-bit         
        AdpcmSbpro3    = 69648, // ADPCM Sound Blaster Pro 2.6-bit       
        AdpcmSbpro4    = 69647, // ADPCM Sound Blaster Pro 4-bit    
        AdpcmSwf       = 69645, 
        AdpcmThp       = 69650, 
        AdpcmAa        = 69640,
        AdpcmVima      = 69662, // ADPCM VIMA
        AdpcmYamaha    = 69646, // APDCM Yamaha AICA                                        | NAudio#YamahaAdpcm
        Aac            = 86018, // Advanced Audio Coding
        AacLatm        = 86066, // AAC LATM             
        Ac3            = 86019, // Dolby Digital AC-3                                       | CoreAudio#AC3, MediaFoundation               
        Adts           = 0,     //                                                          | MediaFoundation
        Alac           = 86032, // Apple Lossless Audio Codec                               | CoreAudio#AppleLossless, MediaFoundation
        Als            = 86062, // MPEG-4 Audio Lossless Coding
        // Ambe        = 0,     // Advanced Multi Band Excitation                           | MediaFoundation
        AmrNb          = 73728, // Adaptive Multi-Rate Audio Codec [.amr, .3ga]             | MediaFoundation
        AmrWb          = 73729, // G.722.2                                                  | CoreAudio#AMR_WB
        AmrWp          = 0,     //                                                          | MediaFoundation
        Ape            = 86049, // Monkey's Audio     
        Asao           = 86050, // Nellymoser Asao
        Atrac1         = 86063, // Adaptive Transform Acoustic Coding  
        Atrac3         = 86047, // Adaptive Transform Acoustic Coding 3     
        Atrac3p        = 86056, // ATRAC3+
        Atrac3Al       = 88078, // Adaptive Transform Acoustic Coding 3 Advanced Lossless
        Atrac3Pal      = 88079,
        Bv16           = 225,   // BroadVoice
        Bv32           = 226,   // BroadVoice
        BinkAudioRdft  = 86064, // Bink Audio
        BinkAudioDct   = 86065,
        Celt           = 86068, // CELT
        ComfortNoise   = 86078,
        Cook           = 86036, // RealAudio cook
        Dts            = 86020, // Digital Theater Systems                                  | MediaFoundation
        DsicinAudio    = 86042, // Delphine Software International CIN audio
        DssSSp         = 86083, // Digital Speech Standard (Standard Play Mode)
        DsdLsbf        = 88069, // Direct Stream Digital
        DsdMsbf        = 88070,
        DsdLsbfPlanar  = 88071,
        DsdMsbfPlanar  = 88072,
        DvAudio        = 86022, // DV audio
        Eac3           = 86057, // ATSC A/52B 
        Evrc           = 88067, // Enhanced Variable Rate Codec
        Flac           = 86028, // Free Lossless Audio Codec                                | MediaFoundation
        G710           = 0,     // 
        G711           = 0,     // 
        G719           = 0,     // 
        G722           = 69660, // G.722 ADPCM
        G722_1         = 0,     // 
        G722_2         = AmrWb, // 
        G723_1         = 86069, //                                                      
        G726           = 69643, // G.726 ADPCM	                                    
        G728           = 0,     //                                                        
        G729           = 86070, //                                               
        Gsm            = 86034, // GSM      
        Gsm_ms         = 86046, // GSM (Microsoft)
        Iac            = 86075, // Indeo Audio Coder
        Imc            = 86043, // Intel Music Coder
        InterplayAcm   = 88074, // Interplay ACM	
        InterplayDpcm  = 81921, // Interplay DPCM
        Mace3          = 86025, // Macintosh Audio Compression/Expansion 3:1                | CoreAudio       
        Mace6          = 86026, // Macintosh Audio Compression/Expansion 6:1                | CoreAudio
        MetaSound      = 86080, // Voxware MetaSound
        Mlp            = 86045, // Meridian Lossless Packing
        Mp1            = 86059, // MPEG-1 Audio Layer I                               
        Mp2            = 86016, // MPEG-1 Audio Layer II                                 
        Mp3            = 86017, // MPEG-1 Audio Layer III                                   | MediaFoundation
        Mp3Adu         = 86029,
        Mp3On4         = 86030,
        Musepack7      = 86044, // Musepack SV7
        Musepack8      = 86051, // Musepack SV8
        Ofr            = 0,     // OptimFROG
        Opus           = 86077, //    
        PafAudio       = 86081, // Amazing Studio Packed Animation File Audio
        PcmAlaw        = 65543, // PCM A-law       
        PcmBluray      = 65560,
        PcmDvd         = 65555,
        PcmF16le       = 67586,
        PcmF24le       = 67587,
        PcmF32be       = 65556,
        PcmF32le       = 65557,  // NAudio:IeeeFloat?
        PcmF64be       = 65558,
        PcmF64le       = 65559,
        PcmLxf         = 65561,
        PcmMulaw       = 65542, // PCM mu-law
        PcmS16be       = 65537,
        PcmS16bePlanar = 65566,
        PcmS16le       = 65536,
        PcmS16lePlanar = 65554,
        PcmS24be       = 65549,
        PcmS24lePlanar = 65564,
        PcmS32lePlanar = 65565,
        PcmS24daud     = 65552,
        PcmS24le       = 65548,
        PcmS32be       = 65545,
        PcmS32le       = 65544,
        PcmS64be       = 67585,
        PcmS64le       = 67584,
        PcmS8          = 65540, 
        PcmS8Planar    = 65563, // PCM signed 8-bit planar
        PcmU16be       = 65539,
        PcmU16le       = 65538,
        PcmU24be       = 65551,
        PcmU24le       = 65550,
        PcmU32be       = 65547,
        PcmU32le       = 65546,
        PcmU8          = 65541,
        PcmZork        = 65553, // PCM Zork
        Qcelp          = 86040, // Qualcomm Code Excited Linear Prediction                  | CoreAudio#QUALCOMM, MediaFoundation
        Qdmc           = 86067, // QDesign Music Codec                                      | ffmpeg 3.3
        Qdm2           = 86035, // QDesign Music Codec 2
        Ra144          = 77824, // RealAudio 1.0 (14.4K)
        Ra288          = 77825, // RealAudio 2.0 (28.8K)	
        Ralf           = 86074, // RealAudio Lossless
        RoqDpcm        = 81920, // DPCM id RoQ
        S302m          = 65562, // SMPTE 302M
        Sdx2Dpcm       = 83968,
        Shorten        = 86031, // Shorten      
        Sipr           = 86058, // RealAudio SIPR 
        Snd1           = 86033, // Westwood Audio
        SolDpcm        = 81923, // DPCM Sol
        Sonic          = 88065, // Sonic
        Sonic_LS       = 88066, // Sonic Lossless
        SmackerAudio   = 86039, // Smacker audio
        Speex          = 86052, // Speex                                      
        Tak            = 86079, // Tom's Verlustfreier Audiokompressor  
        TrueSpeech     = 86037,
        TrueHD         = 86061, // TrueHD
        Tta            = 86038, // True Audio                           
        TwinVQ         = 86060, // Transform-domain weighted interleave vector quantization | CoreAudio#MPEG4TwinVQ                           
        Vima           = 69662, // VIMA
        VmdAudio       = 86027, // Sierra VMD audio
        Vorbis         = 86021, //           
        Voxware        = 86048, // Voxware MetaSound	
        WavPack        = 86041, // WavPack [wv]            
        Wma1           = 86023, // Windows Media Audio 1                | MediaFoundation
        Wma2           = 86024, // Windows Media Audio 2                | MediaFoundation
        // Wma3           , // 
        Wmal           = 86055, // Windows Media Audio Lossless         | MediaFoundation
        WmaPro         = 86054, // Windows Media Audio Pro	
        WmaVoice       = 86053, // Windows Media Audio Voice	        | NAudio#WmaVoice9
        Xan_Dpcm       = 81922,
        Xma1           = 88075,
        Xma2           = 88076,

        // BmvAudio = 86073,

        // -------------------- Image Codecs ---------------------------------------
        AliasPix            = 176,   //        Alias/Wavefront PIX image
        Bmp                 = 79,    //                                         
        Bpg                 = 0,     //        Better Portable Graphics
        BRenderPix          = 177,   //        BRender PIX image
        Dds                 = 189,   //        DirectDraw Surface
        Dng                 = 0,     //        Digital Negative
        Dpx                 = 129,   //        Digital Picture Exchange
        Exr                 = 179,   //        OpenEXR image
        Gif                 = 98,    //                                                
        Heif                = 0,     //        High Efficiency Image File Format
        Ico                 = 0,               
        Jp2                 = 89,    //        JPEG2000                 
        Jpeg                = 0,     // JPEG | JPEG
        Jxr                 = 0,     //        JPEG-XR
        Nrw                 = 0,     //        Nikon Digital SLR Camera Raw Image File	 
        Pam                 = 67,    //        PNM extension with alpha support.
        Pbm                 = 64,    //                                                
        Pcx                 = 110,   //        PC Paintbrush
        Pgm                 = 65,    //        Portable GrayMap image
        Png                 = 62,    //        PNG                                         
        Pnm                 = 0,     //        
        Ppm                 = 63,    //        Portable PixelMap image
        Psd                 = 32790, //        Photoshop                                      
        Ptx                 = 105,   //        V.Flash PTX format
        Sgi                 = 102,   //        SGI image
        Sunrast             = 111,   //        Sun Rasterfile image
        Svg                 = 0,
        Tiff                = 97,    //                     
        Tga                 = 94,    //        Targa image format
        Vc1Image            = 152,   //        Windows Media Video 9 Image v2
        WebP                = 172,   //                                                
        Wmv3Image           = 151,   //        Windows Media Video 9 Image
        Xpm                 = 32796, //        X BitMap image format           | ffmpeg 3.3
        Xwd                 = 158,
        Xface               = 32779,

        // -------------------- Video Codecs ---------------------------------------
        _4GV            = 88073, //        4GV (Fourth Generation Vocoder)
        _4XM            = 35,    //        4X Movie
        _8BPS           = 49,    //        QuickTime 8BPS video	
        Aasc            = 75,    //        Autodesk Animator Codec      
        Acdv            = 0,     //        ACD Systems Digital Imaging
        Aic             = 169,   // ICOD | Apple Intermediate Codec
        Amv             = 108,   //        AMV Video
        Anm             = 135,   //        Deluxe Paint Animation
        Asv1            = 32,    //        Asus v1	
        Asv2            = 33,    //        Asus v2
        Aura            = 124,   // AURA | Auravision
        Aura2           = 125,   // AUR2 | Auravision 2
        Avrn            = 32777, //        Avid 1:1 10-bit RGB Packer
        Avrp            = 32769, //        Avfid 1:1 10-bit RGB Packer
        Avui            = 32771, //        Avid Meridien Uncompressed
        AV1             = 32797, //        Alliance for Open Media AV1
        Avs             = 83,    //        Audio Video Standard             
        BethsoftVid     = 104,   //        Bethesda VID               
        Blackbird       = 901,   //            
        Bink            = 136,   // BINK | Bink Video
        Bfi             = 118,   //        Brute Force & Ignorance
        BmvVideo        = 154,   //        Discworld II BMV video
        C93             = 103,   //        Interplay C93	
        Cavs            = 88,    //        Chinese AVS video
        Cdxl            = 159,   // CFHD | Commodore CDXL video
        ClearVideo      = 32795, // UCOD | ClearVideo
        Cscd            = 80,    // CSCD | CamStudio Screen Codec
        Cfhd            = 32784, //        CineForm
        Cinepak         = 44,    // CVID | Cinepak     
        Cllc            = 166,   //        Canopus Lossless
        Cljr            = 37,    // CLJR | Cirrus Logic AccuPak	
        Cmv             = 119,   //        Electronic Arts CMV video
        Cpia            = 32778, //        CPiA
        Cyuv            = 27,    //        Creative YUV
        Daala           = 32783, //        
        Dfa             = 150,   //        Chronomaster DFA
        Dirac           = 117,   // BBCD | Dirac            
        DnxHd           = 100,   //        VC3/DNxHD
        DsicInVideo     = 95,    //        Delphine Software International CIN video
        DV              = 25,    // CDVC | Digital Video               
        Dxa             = 99,    //        ScummVM DXA
        Dxtory          = 156,   // xtor | Dxtory
        Dxv             = 190,   //        Resolume DXV
        Escape124       = 116,   //        Escape 124
        Escape130       = 170,   //        Escape 130
        Fic             = 175,   //        Mirillis FIC
        Ffvhuff         = 68,    //        Huffyuv FFmpeg variant
        Flic            = 51,    // FLIC | Autodesk Animator Flic video               
        FlashSv         = 87,    //        Flash Screen Video v1
        FlashSv2        = 132,   //        Flash Screen Video v2
        Flv1            = 22,    //        FLV
        Ffv1            = 34,    // FFV1 | FFmpeg video codec #1	
        Fraps           = 77,    // FPS1 | Fraps            
        Fmvc            = 32793, //       FM Screen Capture Codec
        G2m             = 171,   //       Go2Meeting
        Gdv             = 0,     //       Gremlin Digital Video
        Hap             = 188,   //       Vidvox Hap
        H261            = 4,     // H261 | H.261               
        H262            = 2,     // H262 | MPEG-2               
        H263            = 5,     // H263 | MPEG-3        
        H263P           = 20,    //        MPEG-3        
        H263I           = 21,    //        MPEG-3        
        H264            = 28,    // H264 | MPEG-4 (mp4)  
        Hevc            = 174,   //        H.265     
        Hnm4Video       = 173,   //        HNM 4 Video
        Hqx             = 185,   //        Canopus HQX	
        Huffyuv         = 920,             
        Idcin           = 48,    //        id Cinematic format
        Ilbc            = 86076, //        Internet Low Bitrate Codec
        Indeo2          = 76,    // RT21 | Intel Indeo 2
        Indeo3          = 29,    // IV31 | Intel Indeo 3
        Indeo4          = 112,   // IV41 | Intel Indeo 4
        Indeo5          = 113,   // IV50 | Intel Indeo 5
        InterplayVideo  = 40,              
        JV              = 149,   //        Bitmap Brothers JV Video
        Kgv1            = 138,   // KGV1 | Kega Video
        Kmvc            = 86,    // KMVC | Karl Morton's video codec
        Lagarith        = 147,   // LAGS | Lagarith
        Loco            = 73,    // LOCO | LOCO
        M101            = 32786, // MMES | Matrox Uncompressed SDf
        Mad             = 130,   //        Electronic Arts Madcow Video 
        MagicYuv        = 32787, // ?    | MagicYUV
        Mimic           = 114,   // ML20 | Mimic
        Mdec            = 38,    //        Sony PlayStation Motion DECoder
        Mmvideo         = 81,    //        American Laser Games MM Video
        MotionPixels    = 120,   // MVI1 | Motion Pixels video
        Mpeg1           = 1,     // MPG1 | MPEG-1 video
        Mpeg2           = H262,
        Mpeg4           = 13,
        Mszh            = 54,    // MSZH | LCL (LossLess Codec Library) 
        MSMpeg4v1       = 15,    //        MPEG-4 part 2 Microsoft variant version 1
        MSMpeg4v2       = 16,    //        MPEG-4 part 2 Microsoft variant version 2
        MSMpeg4v3       = 17,    //        MPEG-4 part 2 Microsoft variant version 3
        Msa1            = 163,   //        MS ATC Screen codec
        Mss1            = 162,   // MSS1 | Microsoft Screen Codec
        Mss2            = 167,   // MSS2 | Microsoft Screen Codec
        Mts2            = 165,   // MTS2 | Expression Encoder Screen Capture Codec
        Mjpeg           = 8,     // MJPG | Motion JPEG 
        // Mj2,                  //        Motion JPEG 2000  
        Mvc1            = 183,
        Mvc2            = 184,
        MxPeg           = 146,   //        MxPEG
        Nuv             = 85,    //        NuppelVideo
        PafVideo        = 178,   //        Amazing Studio Packed Animation File Video  
        ProRes          = 927,   // ?    | Apple ProRes
        Pixlet          = 32791, //        Apple Pixlet                                 | ffmpeg 3.3
        Qdraw           = 59,    // QDRW | Apple QuickDraw
        Qpeg            = 61,    // QPEG | Q-team QPEG
        Qtrle           = 56,    //        Quicktime Animation 
        R10k            = 145,   // R10K | AJA Kona 10-bit RGB Codec
        Rl2             = 115,   //        RL2 video	
        Roq             = 39,    //        id RoQ video
        Rpza            = 43,    // RPZA | Apple QuickTime video	
        Rscc            = 192,   //        Rsupport Screen Capture Codec
        Rv10            = 6,     // RV10 | RealVideo 1.0	  
        Rv20            = 7,     // RV20 | RealVideo 2.0	  
        Rv30            = 69,    // RV30 | RealVideo 3.0
        Rv40            = 70,    // RV40 | RealVideo 4.0
        Sanm            = 181,   // 
        Screenpresso    = 191,   //        Screenpresso
        Scpr            = 32794, //        ScreenPressor                                | ffmpeg 3.3
        SheerVideo      = 32788, // 
        SgiRle          = 182,   //        SGI RLE 8-bit
        Smk             = 84,    //        Smacker video
        Snow            = 32780, //        FFmpeg Snow
        SpeedHq         = 32792, //        Newtek SpeedHQ	                            | ffmpeg 3.3
        Smc             = 50,    //        QuickTime Graphics
        Smv             = 88068, //        Sigmatel Motion Video
        SmvJpeg         = 32781, //        Sigmatel Motion Video
        Sp5x            = 11,    //        Sunplus JPEG 
        Svq1            = 23,    //        Sorenson Vector Quantizer 1
        Svq3            = 24,    //        Sorenson Vector Quantizer 3
        Tdsc            = 186,   //        TDSC
        Theora          = 31,    //        Based on VP3
        Duck            = 52,    //        Duck TrueMotion 1.0	(ffmpeg: TRUEMOTION1)
        Thp             = 101,   //        Nintendo Gamecube THP video
        TiertexSeqVideo = 96,    //        Tiertex Limited SEQ video
        Tgv             = 121,   //        EA TGV video
        Tmv             = 127,   //        8088flex TMV
        Tgq             = 122,   //        EA TGQ video
        Tqi             = 123,   //        EA TQI video
        Tm20            = 78,    // TM20 | Duck TrueMotion 2.0	 (ffmpeg: TRUEMOTION2)
        Tr20            = 32785, //        Duck TrueMotion 2.0 RT	(ffmpeg: TRUEMOTION2RT)
        Tscc            = 57,    // TSCC | TechSmith Screen Capture Codec  
        Tscc2           = 164,   //        TechSmith Screen Codec 2
        Txd             = 106,   //        Renderware TXD 
        Ulti            = 58,    // ULTI | IBM UltiMotion
        UtVideo         = 153,   // ULRA | Ut Video
        V210            = 128,   // V210 | V210 Video Picture Encoding
        VB              = 109,   //        Beam Software VB
        Vble            = 155,   // VBLE | VBLE Lossless Codec	
        Vc1             = 71,    // WVC1 | SMPTE VC-1
        Vcr1            = 36,    // VCR1 | ATI VCR1
        Vixl            = 60,    //        Miro VideoXL
        VmdVideo        = 53,    //        Sierra VMD video
        Vmnc            = 90,    //        VMware Screen Codec
        Vp3             = 30,    // VP30 | On2 Vp3         
        Vp5             = 91,    // VP50 | On2 Vp5         
        Vp6             = 92,    // VP60 | On2 TrueMotion VP6          
        Vp6A            = 107,   //        VP6 (Alpha)            
        Vp6E            = 958,   // 
        Vp6F            = 93,    //        VP6 (Flash)                
        Vp7             = 180,   // VP70 | On2 VP7 (VP71) 
        Vp8             = 140,   // VP80 | VP8
        Vp9             = 168,   //        Google VP9             
        Vqa             = 45,    //        Westwood Studios Vector Quantized Animation	
        Wmv1            = 18,    // WMV1 | Windows Media Video 7
        Wmv2            = 19,    // WMV2 | Windows Media Video 8   
        Wmv3            = 72,    // WMV3 | Windows Media Video 9
        Wnv1            = 74,    //        Winnov WNV1
        XanWc3          = 41,    //        Wing Commander III / Xan	
        XanWc4          = 42,    //        Wing Commander IV / Xan
        TargaY216       = 32773, //        Pinnacle TARGA CineWave YUV16
        Ylc             = 32789, //        YUY2 Lossless Codec
        Yop             = 139,   //        Psygnosis YOP
        ZeroCodec       = 161,   //        ZeroCodec Lossless Video
        Zmbv            = 82,    //        Zip Motion Blocks Video

        // Raw Pixel Formats --- 
        _012v           = 32770,  // AVRn | Uncompressed 4:2:2 10-bit
        Ayuv            = 32772,  //        packed MS 4:4:4:4
        R210            = 134,    // r210 | RGB 10-bit
        V210X           = 126,    //        4:2:2 10-bit
        V308            = 32774,  //        Uncompressed packed 4:4:4
        V408            = 32775,  //        Uncompressed packed QT 4:4:4:4
        V410            = 157,    //        Uncompressed 4:4:4 10-bit
        Y41p            = 32768,  // Y41P | Uncompressed YUV 4:1:1 12-bit
        Yuv4            = 32776,  //        Uncompressed packed 4:2:0

        // -------------------- Subtitle Codecs ---------------------------------------
        Ass         = 96269,
        Cmml        = 0,      //            Continuous Media Markup Language
        DvbSubtitle = 94209,  //            DVB subtitles 
        DvdSubtitle = 94208,  //            
        DvbTeletext = 94215,  //            DVB teletext
        Eia608      = 96257,  //            EIA-608
        Idf         = 100354, //            iCEDraw text
        Jacosub     = 96258,  //            JACOsub
        MicroDvd    = 96256,  //            MicroDVD subtitle
        Mpl2        = 96266,                
        Pjs         = 96268,  //            Phoenix Japanimation Society
        RealText    = 96260,                
        Sami        = 96259,  //            SAMI
        Srt         = 94216,  //            SubRip
        Ssa         = 94212,                
        Stl         = 96261,  //            Spruce format
        SubRip      = 96264,  //            SubRip subtitle with embedded timing
        SubViewer   = 96263,  //            SubViewer
        SubViewer1  = 96262,  //            
        TimedId3    = 100358, //            timed ID3 metadata
        VPlayer     = 96267,  //            VPlayer
        WebVtt      = 96265,  //            WebVTT subtitle
        Xsub        = 94211,  //            XSUB

        // Fonts
        Otf = 100355,
        Ttf = 98304,
    }
}