using Carbon.Media.Formats;

namespace Carbon.Media
{
    public enum CodecId : uint
    {
        Unknown = 0,

        // -------------------- Audio Codecs (2000) -------------------------------------- | FFMPEG
        _8svxExp       = 2000, // 8SVX exponential                                         |       
        _8svxFib       = 2001, // 8SVX fibonacci                                           |       
        AdpcmImaOki    = 2100, //                                                          |       
        AdpcmDtk       = 2101, // ADPCM Nintendo Gamecube DTK                              |       
        AdpcmImaRad    = 2102, // ADPCM IMA Radical                                        |       
        AdpcmG726Le    = 2103, //                                                          |       
        AdpcmThpLe     = 2104, // ADPCM Nintendo THP                                       |       
        AdpcmPsx       = 2105, //                                                          |       
        AdpcmAica      = 2106, //                                                          |       
        AdpcmImaDat4   = 2107, //                                                          |       
        AdpcmMtaf      = 2108, //                                                          |       
        Adpcm4xm       = 2109, // ADPCM 4X Movie                                           |       
        AdpcmAdx       = 2110, // SEGA CRI ADX ADPCM                                       |       
        AdpcmAfc       = 2111, // ADPCM Nintendo Gamecube AFC                              |       
        AdpcmCT        = 2112, // ADPCM Creative Technology                                |       
        AdpcmEa        = 2113, // ADPCM Electronic Arts                                    |       
        AdpcmEaMaxisXa = 2114, //                                                          |       
        AdpcmEaR1      = 2115, // ADPCM Electronic Arts R1                                 |       
        AdpcmEaR2      = 2116, // ADPCM Electronic Arts R2                                 |       
        AdpcmEaR3      = 2117, // ADPCM Electronic Arts R3                                 |       
        AdpcmEaXas     = 2118, //                                                          |       
        AdpcmImaApc    = 2119, //                                                          |       
        AdpcmImaEASead = 2120, //                                                          |       
        AdpcmImaEAEacs = 2121, //                                                          |       
        AdpcmImaIss    = 2122, //                                                          |       
        AdpcmImaAmv    = 2123, //                                                          |       
        AdpcmImaQT     = 2124, //                                                          |       
        AdpcmImaWav    = 2125, // ADPCM IMA WAV                                            |       
        AdpcmImaDk3    = 2126, // ADPCM IMA Duck DK3                                       |       
        AdpcmImaDk4    = 2127, // ADPCM IMA Duck DK4                                       |       
        AdpcmImaWs     = 2128, //                                                          |       
        AdpcmImaSmJpeg = 2129, //                                                          |       
        AdpcmMS        = 2130, // ADPCM Microsoft                                          |       
        AdpcmSbpro2    = 2131, // ADPCM Sound Blaster Pro 2-bit                            |       
        AdpcmSbpro3    = 2132, // ADPCM Sound Blaster Pro 2.6-bit                          |       
        AdpcmSbpro4    = 2133, // ADPCM Sound Blaster Pro 4-bit                            |       
        AdpcmSwf       = 2134, //                                                          |       
        AdpcmThp       = 2135, //                                                          |       
        AdpcmAa        = 2136, //                                                          |       
        AdpcmVima      = 2137, // ADPCM VIMA                                               |       
        AdpcmYamaha    = 2138, // APDCM Yamaha AICA                                        |         
        Aac            = 2200, // Advanced Audio Coding                                    |       
        AacLatm        = 2201, // AAC LATM                                                 |       
        Ac3            = 2202, // Dolby Digital AC-3                                       |                    
        Adts           = 2203, //                                                          |       
        Alac           = 2204, // Apple Lossless Audio Codec                               |       
        Als            = 2205, // MPEG-4 Audio Lossless Coding                             |       
        // Ambe        = 2206  // Advanced Multi Band Excitation                           |       
        AmrNb          = 2207, // Adaptive Multi-Rate Audio Codec [.amr, .3ga]             |       
        AmrWb          = G722_2, // G.722.2                                                |       
        AmrWp          = 2209, //                                                          |       
        Ape            = 2210, // Monkey's Audio                                           |       
        Aptx           = 2211, // aptX                                                     |       
        AptxHd         = 2212, // aptX HD                                                  |       
        Asao           = 2213, // Nellymoser Asao                                          |       
        Atrac1         = 2214, // Adaptive Transform Acoustic Coding                       |       
        Atrac3         = 2215, // Adaptive Transform Acoustic Coding 3                     |       
        Atrac3p        = 2216, // ATRAC3+                                                  |       
        Atrac3Al       = 2217, // Adaptive Transform Acoustic Coding 3, Advanced Lossless  |       
        Atrac3Pal      = 2218, //                                                          |       
        Bv16           = 2219, // BroadVoice                                               |       
        Bv32           = 2220, // BroadVoice                                               |       
        BinkAudioRdft  = 2221, // Bink Audio                                               |       
        BinkAudioDct   = 2222, //                                                          |       
        BmvAudio       = 2225, //                                                          |       
        Celt           = 2230, // CELT                                                     |       
        Codec2         = 2231, // Codec 2                                                  | v4.0  
        ComfortNoise   = 2232, //                                                          |       
        Cook           = 2233, // RealAudio cook                                           |       
        Dst            = 2240, // Direct Stream Transfer                                   |       
        Dts            = 2241, // Digital Theater Systems                                  |       
        DsicinAudio    = 2242, // Delphine Software International CIN audio                |       
        DssSSp         = 2243, // Digital Speech Standard (Standard Play Mode)             |       
        DsdLsbf        = 2244, // Direct Stream Digital                                    |       
        DsdMsbf        = 2245, //                                                          |       
        DsdLsbfPlanar  = 2246, //                                                          |       
        DsdMsbfPlanar  = 2247, //                                                          |       
        DvAudio        = 2248, // DV audio                                                 |       
        Eac3           = 2250, // ATSC A/52B                                               |       
        Evrc           = 2251, // Enhanced Variable Rate Codec                             |       
        Flac           = 2260, // Free Lossless Audio Codec                                |       
        G710           = 2310, //                                                          |       
        G711           = 2311, //                                                          |       
        G719           = 2319, //                                                          |       
        G722           = 2322, // G.722 ADPCM (ffmpeg: ADPCM_G722)                         |       
        G722_1         = 2323, //                                                          |       
        G722_2         = 2324, // AKA AMRWB                                                |       
        G723_1         = 2325, //                                                          |       
        G726           = 2326, // G.726 ADPCM                                              |                 
        G728           = 2328, //                                                          |       
        G729           = 2329, //                                                          |       
        GremlinDpcm    = 2350, //                                                          |       
        Gsm            = 2351, // GSM                                                      |       
        GsmMicrosoft   = 2352, // GSM (Microsoft)                                          |       
        Iac            = 2400, // Indeo Audio Coder                                        |       
        Imc            = 2401, // Intel Music Coder                                        |       
        InterplayAcm   = 2402, // Interplay ACM	                                           |       
        InterplayDpcm  = 2403, // Interplay DPCM                                           |       
        Mace3          = 2404, // Macintosh Audio Compression/Expansion 3:1                |       
        Mace6          = 2405, // Macintosh Audio Compression/Expansion 6:1                |       
        MetaSound      = 2406, // Voxware MetaSound                                        |       
        Mlp            = 2407, // Meridian Lossless Packing                                |       
        Mp1            = 2408, // MPEG-1 Audio Layer I                                     |       
        Mp2            = 2409, // MPEG-1 Audio Layer II                                    |       
        Mp3            = 2410, // MPEG-1 Audio Layer III                                   |       
        Mp3Adu         = 2411, //                                                          |       
        Mp3On4         = 2412, //                                                          |       
        Musepack7      = 2413, // Musepack SV7                                             |       
        Musepack8      = 2414, // Musepack SV8                                             |       
        Ofr            = 2415, // OptimFROG                                                |       
        Opus           = 2416, //                                                          |       
        PafAudio       = 2600, // Amazing Studio Packed Animation File Audio               |       
        PcmAlaw        = 2601, // PCM A-law                                                |       
        PcmBluray      = 2602, //                                                          |       
        PcmDvd         = 2603, //                                                          |       
        PcmF16le       = 2604, //                                                          |       
        PcmF24le       = 2605, //                                                          |       
        PcmF32be       = 2606, //                                                          |       
        PcmF32le       = 2607, // NAudio:IeeeFloat?                                        |       
        PcmF64be       = 2608, //                                                          |       
        PcmF64le       = 2609, //                                                          |       
        PcmLxf         = 2610, //                                                          |       
        PcmMulaw       = 2611, // PCM mu-law                                               |       
        PcmS16be       = 2612, //                                                          |       
        PcmS16bePlanar = 2613, //                                                          |       
        PcmS16le       = 2614, //                                                          |       
        PcmS16lePlanar = 2615, //                                                          |       
        PcmS24be       = 2616, //                                                          |       
        PcmS24lePlanar = 2617, //                                                          |       
        PcmS32lePlanar = 2618, //                                                          |       
        PcmS24daud     = 2619, //                                                          |       
        PcmS24le       = 2620, //                                                          |       
        PcmS32be       = 2621, //                                                          |       
        PcmS32le       = 2622, //                                                          |       
        PcmS64be       = 2623, //                                                          |       
        PcmS64le       = 2624, //                                                          |       
        PcmS8          = 2625, //                                                          |       
        PcmS8Planar    = 2626, // PCM signed 8-bit planar                                  |       
        PcmU16be       = 2627, //                                                          |       
        PcmU16le       = 2628, //                                                          |       
        PcmU24be       = 2629, //                                                          |       
        PcmU24le       = 2630, //                                                          |       
        PcmU32be       = 2631, //                                                          |       
        PcmU32le       = 2632, //                                                          |       
        PcmU8          = 2633, //                                                          |       
        PcmZork        = 2634, // PCM Zork                                                 |       
        Qcelp          = 2700, // Qualcomm Code Excited Linear Prediction                  |       
        Qdmc           = 2701, // QDesign Music Codec                                      | v3.3 
        Qdm2           = 2702, // QDesign Music Codec 2                                    |       
        Ra144          = 2703, // RealAudio 1.0 (14.4K)                                    |       
        Ra288          = 2704, // RealAudio 2.0 (28.8K)	                                   |       
        Ralf           = 2705, // RealAudio Lossless                                       |       
        RoqDpcm        = 2706, // DPCM id RoQ                                              |       
        S302m          = 2707, // SMPTE 302M                                               |       
        Sbc            = 2708, // SBC                                                      | v4.0 
        Sdx2Dpcm       = 2709, //                                                          |       
        Shorten        = 2710, // Shorten                                                  |       
        Sipr           = 2711, // RealAudio SIPR                                           |       
        Snd1           = 2712, // Westwood Audio                                           |       
        SolDpcm        = 2713, // DPCM Sol                                                 |       
        Sonic          = 2714, // Sonic                                                    |       
        SonicLs        = 2715, // Sonic Lossless                                          |       
        SmackerAudio   = 2716, // Smacker audio                                            |       
        Speex          = 2717, // Speex                                                    |       
        Tak            = 2718, // Tom's Verlustfreier Audiokompressor                      |       
        TrueSpeech     = 2719, //                                                          |       
        TrueHD         = 2720, // TrueHD                                                   |       
        Tta            = 2721, // True Audio                                               |       
        TwinVQ         = 2722, // Transform-domain weighted interleave vector quantization |                   
        Vima           = 2723, // VIMA                                                     |       
        VmdAudio       = 2724, // Sierra VMD audio                                         |       
        Vorbis         = 2725, //                                                          |       
        WavPack        = 2800, // WavPack [wv]                                             |       
        Wma1           = 2801, // Windows Media Audio 1                                    |       
        Wma2           = 2802, // Windows Media Audio 2                                    |       
        Wma3           = 2803, // Windows Media Audio 3                                    |       
        Wmal           = 2811, // Windows Media Audio Lossless                             |       
        WmaPro         = 2812, // Windows Media Audio Pro	                               |       
        WmaVoice       = 2850, // Windows Media Audio Voice	                               |       
        XanDpcm        = 2908, //                                                          |       
        Xma1           = 2909, //                                                          |       
        Xma2           = 2910, //                                                          |       

        // BmvAudio = 86073,

        // -------------------- Image Codecs (4000) ----------------------------------
        AliasPix        = 4000, //      | Alias/Wavefront PIX image
        Apng            = 4040, //      | Animated PNG
        Bmp             = 4101, //      |                                  
        Bpg             = 4143, //      | Better Portable Graphics
        BRenderPix      = 4144, //      | BRender PIX image
        Cur             = 4145, //      | Windows Cursor
        Dds             = 4246, //      | DirectDraw Surface
        Dng             = 4247, //      | Digital Negative
        Dpx             = 4248, //      | Digital Picture Exchange
        Exr             = 4209, //      | OpenEXR image
        Fits            = 4210, //      | Flexible Image Transport System 
        Gif             = 4211, //      |                                         
        Heif            = 4212, //      | High Efficiency Image File Format
        Ico             = 4213, //      | Windows Icon Format
        Jp2             = 4310, //      | JPEG2000                 
        Jpeg            = 4320, // JPEG | JPEG
        Jxr             = 4325, //      | JPEG-XR
        Nrw             = 4330, //      | Nikon Digital SLR Camera Raw Image File	 
        Pam             = 4400, //      | PNM extension with alpha support.
        Pbm             = 4401, //      |                                         
        Pcx             = 4402, //      | PC Paintbrush
        Pgm             = 4403, //      | Portable GrayMap image
        PgmYuv          = 4404, //      | 
        Png             = 4520, //      | PNG                                         
        Pnm             = 4530, //      | 
        Ppm             = 4540, //      | Portable PixelMap image
        Psd             = 4550, //      | Photoshop                                      
        Ptx             = 4624, //      | V.Flash PTX format
        Sgi             = 4625, //      | SGI image
        Sunrast         = 4626, //      | Sun Rasterfile image
        Svg             = 4630, //      | Scalable Vector Graphics
        Tiff            = 4775, //      |              
        Tga             = 4739, //      | Targa image format
        Vc1Image        = 4740, //      | Windows Media Video 9 Image v2
        WebP            = 4890, //      |                                         
        Wmv3Image       = 4891, //      | Windows Media Video 9 Image
        Xpm             = 4892, //      | X BitMap image format           | ffmpeg 3.3, CI
        Xwd             = 4893, //      | X Window Dump image format


        // Raw Pixel Formats --- 
        _012v = 4800, // AVRn | Uncompressed 4:2:2 10-bit
        AYUV            = 4901, //        packed MS 4:4:4:4
        R210            = 4902, // r210 | RGB 10-bit
        V210X           = 4903, //        4:2:2 10-bit
        V308            = 4904, //        Uncompressed packed 4:4:4
        V408            = 4905, //        Uncompressed packed QT 4:4:4:4
        V410            = 4906, //        Uncompressed 4:4:4 10-bit
        Y41P            = 4907, // Y41P | Uncompressed YUV 4:1:1 12-bit
        YUV4            = 4908, //        Uncompressed packed 4:2:0

        // -------------------- Video Codecs (9000) ---------------------------------------
        _4GV            = 9000, //      | 4GV (Fourth Generation Vocoder)
        _4XM            = 9001, //      | 4X Movie
        _8BPS           = 9002, //      | QuickTime 8BPS video	
        Aasc            = 9003, //      || Autodesk Animator Codec      
        Acdv            = 9004, //      | ACD Systems Digital Imaging
        Aic             = 9005, // ICOD | Apple Intermediate Codec
        Amv             = 9006, //      | AMV Video
        Anm             = 9007, //      | Deluxe Paint Animation
        Asv1            = 9011, //      | Asus v1	
        Asv2            = 9012, //      | Asus v2
        Aura            = 9020, // AURA | Auravision
        Aura2           = 9021, // AUR2 | Auravision 2
        Avrn            = 9030, //      | Avid 1:1 10-bit RGB Packer
        Avrp            = 9031, //      | Avfid 1:1 10-bit RGB Packer
        Avui            = 9032, //      | Avid Meridien Uncompressed
        AV1             = 9033, //      | Alliance for Open Media AV1
        Avs             = 9034, //      | Audio Video Standard             
        BethsoftVid     = 9050, //      | Bethesda VID               
        Blackbird       = 9051, //      |     
        Bink            = 9052, // BINK | Bink Video
        Bfi             = 9053, //      | Brute Force & Ignorance
        BmvVideo        = 9054, //      | Discworld II BMV video
        C93             = 9100, //      | Interplay C93	
        Cavs            = 9101, //      | Chinese AVS video
        Cdxl            = 9102, // CFHD | Commodore CDXL video
        ClearVideo      = 9103, // UCOD | ClearVideo
        Cscd            = 9104, // CSCD | CamStudio Screen Codec
        Cfhd            = 9105, //      | CineForm
        Cinepak         = 9106, // CVID | Cinepak     
        Cllc            = 9107, //      | Canopus Lossless
        Cljr            = 9108, // CLJR | Cirrus Logic AccuPak	
        Cmv             = 9109, //      | Electronic Arts CMV video
        Cpia            = 9110, //      | CPiA
        Cyuv            = 9111, //      | Creative YUV
        Daala           = 9120, //      | 
        Dfa             = 9121, //      | Chronomaster DFA
        Dirac           = 9122, // BBCD | Dirac            
        DnxHd           = 9123, //      | VC3/DNxHD
        DsicInVideo     = 9124, //      | Delphine Software International CIN video
        Duck            = 9530, //      | Duck TrueMotion 1.0	(ffmpeg: TRUEMOTION1)
        DV              = 9135, // CDVC | Digital Video               
        Dxa             = 9136, //      | ScummVM DXA
        Dxtory          = 9137, // xtor | Dxtory
        Dxv             = 9138, //      | Resolume DXV
        Escape124       = 9150, //      | Escape 124
        Escape130       = 9151, //      | Escape 130
        Fic             = 9202, //      | Mirillis FIC
        Ffvhuff         = 9203, //      | Huffyuv FFmpeg variant
        Flic            = 9204, // FLIC | Autodesk Animator Flic video               
        FlashSv         = 9205, //      | Flash Screen Video v1
        FlashSv2        = 9206, //      | Flash Screen Video v2
        Flv1            = 9207, //      | FLV
        Ffv1            = 9208, // FFV1 | FFmpeg video codec #1	
        Fraps           = 9209, // FPS1 | Fraps            
        Frwu            = 9210, //      | Forward Uncompressed
        Fmvc            = 9211, //      | FM Screen Capture Codec
        G2m             = 9230, //      | Go2Meeting
        Gdv             = 9231, //      | Gremlin Digital Video
        Hap             = 9300, //      | Vidvox Hap
        H261            = 9301, // H261 | H.261               
        H262            = 9302, // H262 | MPEG-2               
        H263            = 9303, // H263 | MPEG-3        
        H263P           = 9304, //      | MPEG-3        
        H263I           = 9305, //      | MPEG-3        
        H264            = 9306, // H264 | MPEG-4 (mp4)  
        Hevc            = 9307, //      | H.265     
        Hnm4Video       = 9308, //      | HNM 4 Video
        Hqx             = 9309, //      | Canopus HQX	
        Huffyuv         = 9310, //      | 
        Idcin           = 9311, //      | id Cinematic format
        Ilbc            = 9312, //      | Internet Low Bitrate Codec
        Indeo2          = 9322, // RT21 | Intel Indeo 2
        Indeo3          = 9323, // IV31 | Intel Indeo 3
        Indeo4          = 9324, // IV41 | Intel Indeo 4
        Indeo5          = 9325, // IV50 | Intel Indeo 5
        InterplayVideo  = 9330, //      | 
        JV              = 9340, //      | Bitmap Brothers JV Video
        Kgv1            = 9341, // KGV1 | Kega Video
        Kmvc            = 9342, // KMVC | Karl Morton's video codec
        Lagarith        = 9343, // LAGS | Lagarith
        Loco            = 9344, // LOCO | LOCO
        M101            = 9401, // MMES | Matrox Uncompressed SDf
        Mad             = 9402, //      | Electronic Arts Madcow Video 
        MagicYuv        = 9403, // ?    | MagicYUV
        Mimic           = 9404, // ML20 | Mimic
        Mdec            = 9405, //      | Sony PlayStation Motion DECoder
        Mmvideo         = 9406, //      | American Laser Games MM Video
        MotionPixels    = 9407, // MVI1 | Motion Pixels video
        Mpeg1           = 9411, // MPG1 | MPEG-1 video
        Mpeg2           = 9412, // MPEG | MPEG-2 video
        Mpeg4           = 9414, //      |
        Mszh            = 9420, // MSZH | LCL (LossLess Codec Library) 
        Mscc            = 9421, //      | Mandsoft Screen Capture Codec
        MSMpeg4v1       = 9422, //      | MPEG-4 part 2 Microsoft variant version 1
        MSMpeg4v2       = 9423, //      | MPEG-4 part 2 Microsoft variant version 2
        MSMpeg4v3       = 9424, //      | MPEG-4 part 2 Microsoft variant version 3
        Msa1            = 9425, //      | MS ATC Screen codec
        Mss1            = 9441, // MSS1 | Microsoft Screen Codec
        Mss2            = 9442, // MSS2 | Microsoft Screen Codec
        Mts2            = 9433, // MTS2 | Expression Encoder Screen Capture Codec
        Mjpeg           = 9440, // MJPG | Motion JPEG 
        Mj2             = 9441, //      | Motion JPEG 2000  
        Mvc1            = 9451, //      |
        Mvc2            = 9452, //      |
        MxPeg           = 9460, //      | MxPEG
        Nuv             = 9470, //      | NuppelVideo
        PafVideo        = 9480, //      | Amazing Studio Packed Animation File Video  
        ProRes          = 9481, // ?    | Apple ProRes
        Pixlet          = 9482, //      | Apple Pixlet                                 | ffmpeg 3.3
        Qdraw           = 9483, // QDRW | Apple QuickDraw
        Qpeg            = 9484, // QPEG | Q-team QPEG
        Qtrle           = 9485, //      | Quicktime Animation 
        R10k            = 9510, // R10K | AJA Kona 10-bit RGB Codec
        Rl2             = 9512, //      | RL2 video	
        Roq             = 9520, //      | id RoQ video
        Rpza            = 9521, // RPZA | Apple QuickTime video	
        Rscc            = 9522, //      | Rsupport Screen Capture Codec
        Rv10            = 9531, // RV10 | RealVideo 1.0	  
        Rv20            = 9532, // RV20 | RealVideo 2.0	  
        Rv30            = 9533, // RV30 | RealVideo 3.0
        Rv40            = 9534, // RV40 | RealVideo 4.0
        Sanm            = 9540, //      |
        Screenpresso    = 9541, //      | Screenpresso
        Scpr            = 9542, //      | ScreenPressor                                | ffmpeg 3.3
        SheerVideo      = 9543, //      |
        SgiRle          = 9544, //      | SGI RLE 8-bit
        Smk             = 9545, //      | Smacker video
        Snow            = 9546, //      | FFmpeg Snow
        SpeedHq         = 9547, // SHQ2 | Newtek SpeedHQ	                           | ffmpeg 3.3
        Smc             = 9548, //      | QuickTime Graphics
        Smv             = 9549, //      | Sigmatel Motion Video
        SmvJpeg         = 9550, //      | Sigmatel Motion Video
        Sp5x            = 9551, // SP5X | Sunplus JPEG 
        Srgc            = 9552, //      | Screen Recorder Gold Codec
        Svq1            = 9561, // SVQ1 | Sorenson Vector Quantizer 1
        Svq3            = 9562, // SVQ2 | Sorenson Vector Quantizer 3
        Tdsc            = 9570, //      | TDSC
        Theora          = 9571, //      | Based on VP3
        TargaY216       = 9573, //      | Pinnacle TARGA CineWave YUV16
        Thp             = 9574, //      | Nintendo Gamecube THP video
        TiertexSeqVideo = 9575, //      | Tiertex Limited SEQ video
        Tgv             = 9576, //      | EA TGV video
        Tmv             = 9577, //      | 8088flex TMV
        Tgq             = 9578, //      | EA TGQ video
        Tqi             = 9579, //      | EA TQI video
        Tm20            = 9580, // TM20 | Duck TrueMotion 2.0	    (ffmpeg: TRUEMOTION2)
        Tr20            = 9581, //      | Duck TrueMotion 2.0 RT	(ffmpeg: TRUEMOTION2RT)
        Tscc            = 9582, // TSCC | TechSmith Screen Capture Codec  
        Tscc2           = 9583, //      | TechSmith Screen Codec 2
        Txd             = 9584, //      | Renderware TXD 
        Ulti            = 9601, // ULTI | IBM UltiMotion
        UtVideo         = 9602, // ULRA | Ut Video
        V210            = 9603, // V210 | V210 Video Picture Encoding
        VB              = 9604, //      | Beam Software VB
        Vble            = 9605, // VBLE | VBLE Lossless Codec	
        Vc1             = 9606, // WVC1 | SMPTE VC-1
        Vcr1            = 9607, // VCR1 | ATI VCR1
        Vixl            = 9608, //      | Miro VideoXL
        VmdVideo        = 9609, //      | Sierra VMD video
        Vmnc            = 9610, //      | VMware Screen Codec
        Vp3             = 9623, // VP30 | On2 Vp3         
        Vp5             = 9624, // VP50 | On2 Vp5         
        Vp6             = 9625, // VP60 | On2 TrueMotion VP6          
        Vp6A            = 9626, // VP6A | VP6 (Alpha)            
        Vp6E            = 9627, //      |
        Vp6F            = 9628, //      | VP6 (Flash)                
        Vp7             = 9629, // VP70 | On2 VP7 (VP71) 
        Vp8             = 9630, // VP80 | VP8
        Vp9             = 9631, //      | Google VP9             
        Vqa             = 9632, //      | Westwood Studios Vector Quantized Animation	
        Wmv1            = 9701, // WMV1 | Windows Media Video 7
        Wmv2            = 9702, // WMV2 | Windows Media Video 8   
        Wmv3            = 9793, // WMV3 | Windows Media Video 9
        Wnv1            = 9720, //      | Winnov WNV1
        XanWc3          = 9903, //      | Wing Commander III / Xan	
        XanWc4          = 9904, //      | Wing Commander IV / Xan
        Xface           = 9910, //      |
        Ylc             = 9911, //      | YUY2 Lossless Codec
        Yop             = 9920, //      | Psygnosis YOP
        ZeroCodec       = 9950, //      | ZeroCodec Lossless Video
        Zmbv            = 9951, //      | Zip Motion Blocks Video

        // Fonts (10,000) ----------------------------
        Otf = FontFormat.Otf,
        Ttf = FontFormat.Ttf,

        // -------------------- Subtitle Codecs (100) ---------------------------------------
        // See: https://en.wikipedia.org/wiki/Category:Subtitle_file_formats

        Ass         = 100_001, //
        Cmml        = 100_002, //      | Continuous Media Markup Language
        DvbSubtitle = 100_003, //      | DVB subtitles 
        DvdSubtitle = 100_004, //      | 
        DvbTeletext = 100_005, //      | DVB teletext
        Eia608      = 100_006, //      | EIA-608
        Idf         = 100_007, //      | iCEDraw text
        Jacosub     = 100_008, //      | JACOsub
        MicroDvd    = 100_009, //      | MicroDVD subtitle
        MovText     = 100_500, //
        Mpl2        = 100_510, //      |    
        PjsSubtitle = 100_511, //      | Phoenix Japanimation Society
        RealText    = 100_512, //      |   
        Sami        = 100_513, //      | Synchronized Accessible Media Interchange
        Srt         = 100_514, //      | SubRip
        Ssa         = 100_515, //      |   
        Stl         = 100_516, //      | Spruce format
        SubRip      = 100_517, //      | SubRip subtitle with embedded timing
        SubViewer   = 100_518, //      | SubViewer
        SubViewer1  = 100_519, //      | 
        TimedId3    = 100_520, //      | timed ID3 metadata
        VPlayer     = 100_521, //      | VPlayer
        WebVtt      = 100_522, //      | WebVTT subtitle
        Xsub        = 100_723, //      | XSUB      
    }
}